version: '3.8'

# Task runner configuration for non-postgres services
# Usage: docker-compose -f docker-compose.task.yml run --rm mcp-task [ARGS]

services:
  mcp-task:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-arena:latest
    container_name: mcp-task-runner
    environment:
      # Environment variables will be loaded from .mcp_env file
      DUMMY: "placeholder"
    volumes:
      # Mount results directory
      - ./results:/app/results
      # Mount .mcp_env for configuration
      - ./.mcp_env:/app/.mcp_env:ro
      # Mount notion_state.json if it exists
      - ./notion_state.json:/app/notion_state.json:ro
    networks:
      - mcp-task-network
    stdin_open: true
    tty: true
    # Override with actual command when running
    command: ["python3", "-m", "pipeline", "--help"]

networks:
  mcp-task-network:
    driver: bridge
    name: mcp-task-network